list_of_strings = ["Orange", "Pear", "Kiwi", "Apple"]
list_of_numbers = [1, 3, 45, 6, 3, 98, 30, 45]
print(list_of_strings)
print(list_of_numbers)
list_of_numbers.sort()
list_of_strings.sort()
print(list_of_strings)
print(list_of_numbers)
list_of_numbers.append(100)
print(list_of_numbers)
list_of_numbers.insert(4,10)
print(list_of_numbers)
list_of_numbers.pop()
print(list_of_numbers)
list_of_numbers.pop(4)
print(list_of_numbers)
list_of_numbers.remove(45)
print(list_of_numbers)
list_of_numbers.remove(3)
print(list_of_numbers)