name = input("What's your character name?")
print(name + " is ready for adventure!")
string_looks_like_a_number = input("Enter a number.")
print(isinstance(string_looks_like_a_number, int))
print(string_looks_like_a_number)
number_from_string = int(string_looks_like_a_number)
print(isinstance(string_looks_like_a_number, int))
print(number_from_string)