print("Hello World!")
print("What? I can write anything?!")
print("Hello! How are you?")
print("I am a Computer!")
print("I'm coding in Python!")
print(4+5)
print(10-2)
print(3+1-4)
print("Name: Nathan Carmack")
print("DOB: December 23, 2004")
print("Favorite Holiday: Christmas")
print("Number(0-100):43")